# Assignment Python track Applied Economic Analysis

## plan

Data binnenhalen van CBS. Gegevens per buurt bekijken en kijken wat er hier eventueel te maken zou kunnen hebben met het stemgedrag van bepaalde partijen.

In [20]:
import os 
import pandas as pd
import sqlite3

# Create list of folders
folders = []
for folder in os.walk('Data/'):
    files = []
    for file in folder: 
        files.append(file)
        #data = pd.read_csv(file)
        #con = sqlite3.connect('D:/data/PolProj.db')
        #data.to_sql(file, con  = con)
    folders.append(files)

In [82]:

#from sqlite3 import ParserError
con = sqlite3.connect('D:/data/PolProj.db')
for idx, item in enumerate(folders):
    try:
        for i in enumerate(item[2]):
            location = str(str(item[0])+'/'+str(i[1]))
            temp = pd.read_csv(location, sep = ';')
            try:
                temp.to_sql(str(i[1]), con = con, if_exists = 'replace')
            except sqlite3.OperationalError: 
                print('Double colname, check '+str(i[1]))
                next
    except pd.errors.ParserError: 
        print('Something went wrong with '+str(i[1]))

C:\Users\jjhve\anaconda3\lib\site-packages\pandas\core\generic.py:2872: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(

Double colname, check GR2006_gem.csv
Double colname, check GR2010_gem.csv
Double colname, check GR2014_gem.csv
Something went wrong with WS2019_gem.csv

,RegioNaam,RegioCode,AmsterdamseCode,OuderRegioNaam,OuderRegioCode,Kiesgerechtigden,Opkomst,OngeldigeStemmen,BlancoStemmen,GeldigeStemmen,...,SP (Socialistische Partij),CU_SGP,Democraten 66 (D66),Partij voor de Dieren,Lijst Pim Fortuyn,Partij voor het Noorden,Nieuw Rechts,Leefbaar Europa,Democratisch Europa,Respect.Nu
0,Aa en Hunze,G1680,10787.0,Drenthe,P22,19574,9310,NaN,9.0,9301,...,454,124,336,243,129,267,14,5,7,6
1,Aalburg,G0738,11084.0,Noord-Brabant,P30,8821,3945,NaN,2.0,3943,...,117,1367,46,101,78,0,16,4,5,4
2,Aalsmeer,G0358,11264.0,Noord-Holland,P27,17366,6957,NaN,32.0,6925,...,296,319,335,272,365,6,24,11,13,4
3,Aalten,G0197,11046.0,Gelderland,P25,13975,6594,NaN,8.0,6586,...,503,330,155,150,108,6,7,12,11,7
4,Abcoude,G0305,10712.0,Utrecht,P26,6227,3235,NaN,5.0,3230,...,133,97,211,135,80,4,7,3,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,Zundert,G0879,11192.0,Noord-Brabant,P30,15400,4775,NaN,14.0,4761,...,248,27,142,110,131,3,12,18,1,4
480,Zutphen,G0301,10254.0,Gelderland,P25,27619,11456,NaN,22.0,11434,...,1328,339,522,390,172,14,27,16,24,13
481,Zwartewaterland,G1896,10746.0,Overijssel,P23,15405,7310,NaN,6.0,7304,...,205,2779,70,98,65,11,11,4,3,8
482,Zwijndrecht,G0642,10468.0,Zuid-Holland,P28,34628,13192,NaN,23.0,13169,...,688,1681,412,341,623,10,60,31,15,9
483,Zwolle,G0193,10093.0,Overijssel,P23,85048,37010,NaN,90.0,36920,...,2632,4139,1669,952,538,51,85,56,40,24

In [59]:
lister = [4,5,5,6,3]
str(str(lister[0])+'fiets')

'4fiets'